delete from function_people
where function_id in (
  select f.id
  from functions f
  join areas a on a.id = f.area_id
  where a.name in (
    'ASSOCIADOS',
    'CIENTÍFICO',
    'COMUNICAÇÃO E MARKETING',
    'COMUNIDADE WHATSAPP',
    'COORDENAÇÃO',
    'DIREÇÃO',
    'FINANCEIRO',
    'FORMAÇÃO',
    'FUNDRAISING',
    'IT',
    'LEGAL',
    'PESSOAS E TALENTO',
    'RELAÇÕES INSTITUCIONAIS',
    'RP'
  )
);

delete from functions
where area_id in (
  select id
  from areas
  where name in (
    'ASSOCIADOS',
    'CIENTÍFICO',
    'COMUNICAÇÃO E MARKETING',
    'COMUNIDADE WHATSAPP',
    'COORDENAÇÃO',
    'DIREÇÃO',
    'FINANCEIRO',
    'FORMAÇÃO',
    'FUNDRAISING',
    'IT',
    'LEGAL',
    'PESSOAS E TALENTO',
    'RELAÇÕES INSTITUCIONAIS',
    'RP'
  )
);

insert into functions (
  area_id,
  parent_function_id,
  name,
  description,
  level,
  sort_order,
  status
)
select
  a.id,
  null,
  v.function_name,
  null,
  1,
  v.sort_order,
  'active'::generic_status
from (
  values
    ('DIREÇÃO', 'Definir prioridades estratégicas', 1),
    ('DIREÇÃO', 'Tomar decisões estruturantes', 2),
    ('DIREÇÃO', 'Aprovar planos, posições e orientações críticas', 3),
    ('DIREÇÃO', 'Deliberar sobre matérias sensíveis ou de maior impacto', 4),
    ('DIREÇÃO', 'Validar iniciativas estratégicas, sensíveis, de risco reputacional, jurídico ou financeiro relevante', 5),
    ('DIREÇÃO', 'Aprovar parcerias, posicionamentos e compromissos institucionais críticos', 6),
    ('DIREÇÃO', 'Definir critérios de prioridade entre projetos concorrentes', 7),
    ('DIREÇÃO', 'Acompanhar o alinhamento global da associação com a missão', 8),
    ('DIREÇÃO', 'Rever periodicamente a estratégia e os objetivos anuais', 9),
    ('COORDENAÇÃO', 'Articular áreas e responsáveis', 1),
    ('COORDENAÇÃO', 'Acompanhar execução transversal', 2),
    ('COORDENAÇÃO', 'Controlar o trabalho em curso', 3),
    ('COORDENAÇÃO', 'Identificar bloqueios, atrasos e dependências', 4),
    ('COORDENAÇÃO', 'Reportar à Direção', 5),
    ('COORDENAÇÃO', 'Traduzir decisões da Direção em planos de execução', 6),
    ('COORDENAÇÃO', 'Garantir follow-up de tarefas e prazos', 7),
    ('COORDENAÇÃO', 'Assegurar que nada crítico fica sem responsável', 8),
    ('COORDENAÇÃO', 'Coordenar iniciativas que envolvem várias áreas', 9),
    ('COORDENAÇÃO', 'Sinalizar riscos operacionais e necessidades de reforço', 10),
    ('COORDENAÇÃO', 'Organizar informação de estado da associação', 11),
    ('COORDENAÇÃO', 'Preparar sínteses executivas para apoio à decisão', 12),
    ('ASSOCIADOS', 'Operacionalizar conversão e retenção de associados', 1),
    ('ASSOCIADOS', 'Validar inscrições', 2),
    ('ASSOCIADOS', 'Fazer onboarding (boas vindas + ativar portal)', 3),
    ('ASSOCIADOS', 'Apoiar associados', 4),
    ('ASSOCIADOS', 'Gerir a relação funcional com os associados', 5),
    ('ASSOCIADOS', 'Acompanhar o ciclo de vida do associado', 6),
    ('ASSOCIADOS', 'Atualizar dados e estados dos associados', 7),
    ('ASSOCIADOS', 'Responder a dúvidas sobre adesão, acesso e funcionamento', 8),
    ('ASSOCIADOS', 'Gerir pedidos de alteração, suspensão ou regularização', 9),
    ('ASSOCIADOS', 'Criar experiências de acolhimento e ativação', 10),
    ('ASSOCIADOS', 'Campanhas de conversão de pré-inscritos em associados', 11),
    ('ASSOCIADOS', 'Identificar causas de abandono ou inatividade', 12),
    ('ASSOCIADOS', 'Segmentar associados para melhor acompanhamento', 13),
    ('ASSOCIADOS', 'Articular com Financeiro os fluxos de quotas e donativos', 14),
    ('CIENTÍFICO', 'Definir prioridades temáticas', 1),
    ('CIENTÍFICO', 'Validar rigor técnico-científico', 2),
    ('CIENTÍFICO', 'Rever conteúdos', 3),
    ('CIENTÍFICO', 'Produzir materiais de referência', 4),
    ('CIENTÍFICO', 'Promover literacia em PHDA', 5),
    ('CIENTÍFICO', 'Definir critérios e posições técnicas', 6),
    ('CIENTÍFICO', 'Garantir qualidade e fiabilidade da informação publicada', 7),
    ('CIENTÍFICO', 'Apoiar produção de FAQs, guias e materiais explicativos', 8),
    ('CIENTÍFICO', 'Delimitar o que a Brainstorm recomenda ou não recomenda', 9),
    ('CIENTÍFICO', 'Apoiar enquadramento técnico de campanhas e iniciativas', 10),
    ('CIENTÍFICO', 'Estruturar temas prioritários para comunicação e formação', 11),
    ('CIENTÍFICO', 'Rever conteúdos sobre saúde, educação, direitos e inclusão', 12),
    ('CIENTÍFICO', 'Apoiar estudos, pareceres e reflexão técnica', 13),
    ('CIENTÍFICO', 'Distinguir evidência, opinião e testemunho pessoal', 14),
    ('CIENTÍFICO', 'Atualizar critérios à luz de nova evidência ou novas necessidades', 15),
    ('COMUNICAÇÃO E MARKETING', 'Gerir marca e identidade', 1),
    ('COMUNICAÇÃO E MARKETING', 'Planear campanhas', 2),
    ('COMUNICAÇÃO E MARKETING', 'Gerir redes sociais', 3),
    ('COMUNICAÇÃO E MARKETING', 'Produzir conteúdos editoriais e de comunicação', 4),
    ('COMUNICAÇÃO E MARKETING', 'Enviar newsletters e email marketing', 5),
    ('COMUNICAÇÃO E MARKETING', 'Apoiar captação e engagement de associados', 6),
    ('COMUNICAÇÃO E MARKETING', 'Definir pilares de comunicação', 7),
    ('COMUNICAÇÃO E MARKETING', 'Adaptar mensagens a diferentes públicos', 8),
    ('COMUNICAÇÃO E MARKETING', 'Coordenar calendários editoriais e de campanhas', 9),
    ('COMUNICAÇÃO E MARKETING', 'Criar conteúdos de awareness, conversão e retenção', 10),
    ('COMUNICAÇÃO E MARKETING', 'Desenvolver materiais de divulgação e apresentação', 11),
    ('COMUNICAÇÃO E MARKETING', 'Gerir presença digital corrente da marca', 12),
    ('COMUNICAÇÃO E MARKETING', 'Criar loops entre redes, site, newsletter e associação', 13),
    ('COMUNICAÇÃO E MARKETING', 'Medir desempenho de campanhas e conteúdos', 14),
    ('COMUNICAÇÃO E MARKETING', 'Ajustar formatos, tom e CTAs com base nos resultados', 15),
    ('COMUNIDADE WHATSAPP', 'Organizar a comunidade', 1),
    ('COMUNIDADE WHATSAPP', 'Estruturar grupos temáticos', 2),
    ('COMUNIDADE WHATSAPP', 'Definir regras de participação', 3),
    ('COMUNIDADE WHATSAPP', 'Moderar grupos e interações', 4),
    ('COMUNIDADE WHATSAPP', 'Acolher e encaminhar membros', 5),
    ('COMUNIDADE WHATSAPP', 'Dinamizar participação comunitária', 6),
    ('COMUNIDADE WHATSAPP', 'Gerir a lógica de entrada e permanência nos grupos', 7),
    ('COMUNIDADE WHATSAPP', 'Identificar necessidades emergentes da comunidade', 8),
    ('COMUNIDADE WHATSAPP', 'Encaminhar pessoas para grupos ou recursos adequados', 9),
    ('COMUNIDADE WHATSAPP', 'Prevenir conflitos, desinformação e comportamentos impróprios', 10),
    ('COMUNIDADE WHATSAPP', 'Apoiar moderadores e alinhar critérios de moderação', 11),
    ('COMUNIDADE WHATSAPP', 'Recolher feedback da comunidade', 12),
    ('COMUNIDADE WHATSAPP', 'Transformar sinais da comunidade em inputs para conteúdos, advocacy ou serviços', 13),
    ('COMUNIDADE WHATSAPP', 'Promover sentido de pertença e participação', 14),
    ('COMUNIDADE WHATSAPP', 'Monitorizar saúde e utilidade dos espaços comunitários', 15),
    ('FINANCEIRO', 'Criar e gerir orçamento', 1),
    ('FINANCEIRO', 'Controlar tesouraria', 2),
    ('FINANCEIRO', 'Registar receitas e despesas', 3),
    ('FINANCEIRO', 'Gerir quotas e donativos de associados', 4),
    ('FINANCEIRO', 'Assegurar obrigações fiscais e contabilísticas', 5),
    ('FINANCEIRO', 'Conciliar movimentos financeiros e comprovativos', 6),
    ('FINANCEIRO', 'Organizar pagamentos e reembolsos', 7),
    ('FINANCEIRO', 'Preparar informação para contabilidade', 8),
    ('FINANCEIRO', 'Controlar arquivo administrativo e financeiro', 9),
    ('FINANCEIRO', 'Acompanhar execução orçamental', 10),
    ('FINANCEIRO', 'Produzir mapas simples de receitas, despesas e saldo', 11),
    ('FINANCEIRO', 'Criar alertas para prazos fiscais e pagamentos', 12),
    ('FINANCEIRO', 'Assegurar que despesas têm aprovação e documentação', 13),
    ('FORMAÇÃO', 'Desenhar oferta formativa', 1),
    ('FORMAÇÃO', 'Estruturar programas e sessões', 2),
    ('FORMAÇÃO', 'Preparar materiais', 3),
    ('FORMAÇÃO', 'Articular formadores', 4),
    ('FORMAÇÃO', 'Executar ações de formação', 5),
    ('FORMAÇÃO', 'Avaliar impacto formativo', 6),
    ('FORMAÇÃO', 'Identificar públicos-alvo prioritários', 7),
    ('FORMAÇÃO', 'Adaptar linguagem e formato ao público', 8),
    ('FORMAÇÃO', 'Criar workshops, webinars e sessões de capacitação', 9),
    ('FORMAÇÃO', 'Organizar calendário formativo', 10),
    ('FORMAÇÃO', 'Preparar guiões, apresentações e suportes pedagógicos', 11),
    ('FORMAÇÃO', 'Recolher avaliações de satisfação e aprendizagem', 12),
    ('FORMAÇÃO', 'Melhorar a oferta com base em feedback', 13),
    ('FORMAÇÃO', 'Apoiar formação interna de voluntários, moderadores e equipa', 14),
    ('FORMAÇÃO', 'Estruturar propostas formativas para escolas, famílias, empresas ou profissionais', 15),
    ('FUNDRAISING', 'Angariar donativos', 1),
    ('FUNDRAISING', 'Procurar patrocínios e grants', 2),
    ('FUNDRAISING', 'Negociar parcerias', 3),
    ('FUNDRAISING', 'Gerir protocolos', 4),
    ('FUNDRAISING', 'Desenvolver benefícios para associados', 5),
    ('FUNDRAISING', 'Identificar parceiros estratégicos', 6),
    ('FUNDRAISING', 'Avaliar alinhamento e risco de potenciais parcerias', 7),
    ('FUNDRAISING', 'Preparar propostas de colaboração e contrapartidas', 8),
    ('FUNDRAISING', 'Acompanhar execução de protocolos', 9),
    ('FUNDRAISING', 'Cultivar relação com apoiantes, mecenas e parceiros', 10),
    ('FUNDRAISING', 'Explorar novas fontes de receita não correntes', 11),
    ('FUNDRAISING', 'Estruturar campanhas de fundraising', 12),
    ('FUNDRAISING', 'Preparar candidaturas a apoio e financiamento', 13),
    ('IT', 'Gerir website e landing pages', 1),
    ('IT', 'Administrar ferramentas digitais', 2),
    ('IT', 'Gerir CRM e bases de dados', 3),
    ('IT', 'Implementar integrações e automações', 4),
    ('IT', 'Produzir reporting', 5),
    ('IT', 'Assegurar qualidade de dados', 6),
    ('IT', 'Organizar processos operacionais e base de conhecimento', 7),
    ('IT', 'Manter arquitetura digital da operação', 8),
    ('IT', 'Testar e implementar novas ferramentas', 9),
    ('IT', 'Garantir funcionamento de formulários, fluxos e acessos', 10),
    ('IT', 'Documentar processos digitais', 11),
    ('IT', 'Apoiar automação de inscrições, comunicação e reporting', 12),
    ('IT', 'Organizar informação institucional e operacional em sistemas', 13),
    ('IT', 'Criar dashboards e mapas de acompanhamento', 14),
    ('IT', 'Apoiar futuros sistemas de IA ou chatbot', 15),
    ('IT', 'Reduzir trabalho manual através de desenho de processos', 16),
    ('IT', 'Gerir diretório de profissionais', 17),
    ('LEGAL', 'Garantir enquadramento jurídico da associação', 1),
    ('LEGAL', 'Rever contratos, protocolos e minutas', 2),
    ('LEGAL', 'Assegurar compliance e RGPD', 3),
    ('LEGAL', 'Validar documentos formais', 4),
    ('LEGAL', 'Acompanhar processos de reconhecimento formal', 5),
    ('LEGAL', 'Rever estatutos, regulamentos e atas', 6),
    ('LEGAL', 'Validar consentimentos, políticas e termos', 7),
    ('LEGAL', 'Avaliar risco jurídico de campanhas, iniciativas e modelos operacionais', 8),
    ('LEGAL', 'Apoiar enquadramento legal de benefícios para associados', 9),
    ('LEGAL', 'Validar disclaimers, diretórios e conteúdos sensíveis', 10),
    ('LEGAL', 'Acompanhar cláusulas de responsabilidade, confidencialidade e uso de marca', 11),
    ('LEGAL', 'Apoiar resposta a incidentes com relevância jurídica', 12),
    ('LEGAL', 'Garantir arquivo organizado de documentação legal relevante', 13),
    ('PESSOAS E TALENTO', 'Recrutar voluntários e colaboradores', 1),
    ('PESSOAS E TALENTO', 'Fazer onboarding interno', 2),
    ('PESSOAS E TALENTO', 'Distribuir funções', 3),
    ('PESSOAS E TALENTO', 'Acompanhar disponibilidade e desempenho', 4),
    ('PESSOAS E TALENTO', 'Desenvolver competências', 5),
    ('PESSOAS E TALENTO', 'Assegurar passagem de pasta e continuidade', 6),
    ('PESSOAS E TALENTO', 'Identificar necessidades de capacidade interna', 7),
    ('PESSOAS E TALENTO', 'Mapear competências existentes e em falta', 8),
    ('PESSOAS E TALENTO', 'Apoiar integração de novas pessoas na cultura e nos processos', 9),
    ('PESSOAS E TALENTO', 'Clarificar papéis e responsabilidades', 10),
    ('PESSOAS E TALENTO', 'Reequilibrar carga de trabalho quando necessário', 11),
    ('PESSOAS E TALENTO', 'Apoiar retenção e motivação de voluntários', 12),
    ('PESSOAS E TALENTO', 'Criar condições mínimas de organização interna', 13),
    ('PESSOAS E TALENTO', 'Promover capacitação contínua', 14),
    ('PESSOAS E TALENTO', 'Reduzir dependência de pessoas-chave isoladas', 15),
    ('RELAÇÕES INSTITUCIONAIS', 'Representar a associação externamente', 1),
    ('RELAÇÕES INSTITUCIONAIS', 'Pedir e conduzir reuniões institucionais', 2),
    ('RELAÇÕES INSTITUCIONAIS', 'Fazer advocacy', 3),
    ('RELAÇÕES INSTITUCIONAIS', 'Participar em consultas públicas', 4),
    ('RELAÇÕES INSTITUCIONAIS', 'Propor medidas de inclusão e acomodação', 5),
    ('RELAÇÕES INSTITUCIONAIS', 'Relacionar-se com decisores e entidades', 6),
    ('RELAÇÕES INSTITUCIONAIS', 'Mapear interlocutores institucionais relevantes', 7),
    ('RELAÇÕES INSTITUCIONAIS', 'Preparar propostas e dossiês para reuniões', 8),
    ('RELAÇÕES INSTITUCIONAIS', 'Defender interesses da comunidade PHDA em espaços institucionais', 9),
    ('RELAÇÕES INSTITUCIONAIS', 'Identificar janelas de oportunidade política', 10),
    ('RELAÇÕES INSTITUCIONAIS', 'Acompanhar legislação, medidas e debates relevantes', 11),
    ('RELAÇÕES INSTITUCIONAIS', 'Articular com entidades públicas, reguladores, ordens, escolas e hospitais', 12),
    ('RELAÇÕES INSTITUCIONAIS', 'Promover reconhecimento da Brainstorm como voz credível', 13),
    ('RELAÇÕES INSTITUCIONAIS', 'Transformar necessidades da comunidade em propostas concretas', 14),
    ('RELAÇÕES INSTITUCIONAIS', 'Fazer follow-up persistente junto de interlocutores institucionais', 15),
    ('RP', 'Gerir comunicação institucional', 1),
    ('RP', 'Relacionar-se com imprensa', 2),
    ('RP', 'Preparar posicionamentos públicos', 3),
    ('RP', 'Apoiar porta-vozes', 4),
    ('RP', 'Proteger reputação', 5),
    ('RP', 'Responder a temas sensíveis', 6),
    ('RP', 'Preparar respostas a pedidos de jornalistas', 7),
    ('RP', 'Criar argumentos institucionais e talking points', 8),
    ('RP', 'Identificar oportunidades mediáticas relevantes', 9),
    ('RP', 'Coordenar mensagens em contextos delicados', 10),
    ('RP', 'Apoiar preparação de entrevistas, intervenções e declarações', 11),
    ('RP', 'Acompanhar cobertura mediática', 12),
    ('RP', 'Corrigir ou clarificar perceções públicas incorretas', 13),
    ('RP', 'Assegurar coerência entre visibilidade pública e posicionamento institucional', 14)
) as v(area_name, function_name, sort_order)
join areas a on a.name = v.area_name;
